### ISSUE TITLE
Blazes and Wither Skelletons do spawn at any place in the nether

### ISSUE THREAD

**Issue by midorlo** [tschallacka/MagicCookies#2]
(XPosted from http://minecraft.curseforge.com/mc-mods/231755-magic-cookies?comment=13)

Problem:
Blazes and Wither Skelletons do spawn at any place in the nether

Test scenario:
- Minecraft  1.7.10
- Forge 1492
- Thaumcraft 4.2
- MagicCookies 1.0.6.7
- Automagy 0.26.3
- NO other mods (No NEI, fastcraft etc.)

Further (unsuccesful) tests:
- Changed Forge to 1448, 1450
- Enabled fastcraft
- Any changes to the test scenario came along with a fresh world seed

Logs:
Gone through them, nothing of interest.

Images:
- http://i.imgur.com/WenRMEw.jpg
- http://i.imgur.com/RhVYcPe.png

**Comment by tschallacka** [comment]
Fixed:-) with added bonus that entropy temples are slightly more dangerous to traverse.
