### ISSUE TITLE
ArrayIndexOutOfBoundsException: 8 - 15 ish...

### ISSUE THREAD

**Issue by plaguewolf** [tschallacka/MagicCookies#3]
relevant errors here: http://pastebin.com/JhBG3p9c

happens on world creation.

**Comment by tschallacka** [comment]
those items aren't even in the creative menu. Nei shouldn't list them, they aren't even registered into the registries... I'll report this to nei

**Comment by tschallacka** [comment]
It's a NEI bug. Not a magic cookies bug.

**Comment by plaguewolf** [comment]
hmmmm, worth a mention, reikas dragonapi does things to all items ingame. maybe he is reflecting your items, thus making them appear to be registered?

sorry to bump a dead thread, just some insight i thought about while updating today and getting this error again
