### ISSUE TITLE
Overlapping Research

### ISSUE THREAD

**Issue by Shahelion** [tschallacka/MagicCookies#6]
[00:32:30] [Client thread/FATAL] [FML/MagicCookie]: [Thaumcraft] Research [Thaumium Shears] not added as it overlaps with existing research [Acid Etched Iron]

**Comment by Shahelion** [comment]
So...almost a whole year. Anything?

**Comment by tschallacka** [comment]
Yes. it might get fixed when i have time but now im focussing on the 1.8 update. sorry

Outlook voor Androidhttps://aka.ms/ghei36 downloaden

On Wed, Sep 21, 2016 at 12:27 AM -0700, "Zsashas" <notifications@github.com<mailto:notifications@github.com>> wrote:

So...almost a whole year. Anything?

##

**Comment by Shahelion** [comment]
I imagine this will be dealt with one way or another if the mod gets ported to later MC versions. If not, I'm sure someone will open a new issue.
