### ISSUE TITLE
Possible Golem Issue

### ISSUE THREAD

**Issue by Shahelion** [tschallacka/MagicCookies#7]
This addon does lots of stuff with Golems, so just in case it is the cause...

I can only mark a single location per golem with the bell, no matter what golem type or core.

**Comment by tschallacka** [comment]
is this with the 1.7.10 version? and which golem, which core, and what are you marking.

**Comment by Shahelion** [comment]
Straw and tallow, fill and alchemy,  chests and warded jars, in various combinations.

**Comment by tschallacka** [comment]
thing is, straw and tallow are not my golems. I only do stuff with gold, emerald and my void golem. The golem bell I introduce does have fallbacks for the thaumcraft golems, but it doesn't change the thaumcraft code. If you're having issues with thaumcraft golems you might want to try the thaumcraft golem bell. Also, look for other thaumcraft addons that hook directly into thaumcraft like thaumic tinkers etc..

Try making a new save, see if issue still exists. Then remove magic cookies, see if issue still persists. if it does, it's not my mod that causes your issue.
To narrow in on the cause, keep removing mods, until only thaumcraft remains.
If it then still persists, consider re-downloading thaumcraft, or try a different version of forge.
Also, which java version are you using?
